### ISSUE TITLE
Error in sampling points

### ISSUE THREAD

**Issue by martst** [etiennesky/profiletool#10]
I have been using the profile tool plugin very successfully for some time but I now have an application where I need to know the coordinates of the sample points. I have added a few lines to the software to allow me to output the coordinates as well as the height points. This shows a problem with the calculation of the sample points.

I have a DXF file which I import in QGIS to use as the sample line. When I compare the points that were sampled to the original sample line I find a consistent error of approx 6m in the SE direction. I have tried converting the DXF line to a shapefile and the error is the same. I assume that the error is some type of projection error but all layers, the project and the DXF file are in the same EPSG:27700 (OSGB) projection so no transforms should be happening.

I have created a much simpler DXF file and this doesn't show the error. 

I would be useful for me to have the coordinate output code added permanently. Is that something you would consider?

Do you have any suggestions on the problem with the sample points?

**Comment by borysiasty** [comment]
Could you please make a pull request with the additional code? If you also attached the shp, I could try to investigate that shift.

**Comment by martst** [comment]
Thank you for responding. I have created a pull request for my changes.

I have zipped the shape file that is causing me problems and made it available at the following link
https://www.dropbox.com/s/6wvxm2nl0caksqf/center_line.zip?dl=0

Thanks for you help
Martin

**Comment by borysiasty** [comment]
Thanks, I merged your PR. However, could you please fix the small layout issue it introduced (details in the PR), so we can publish this version? I'll look at the sample data later as soon as I have a free evening (not so soon! :) )

**Comment by borysiasty** [comment]
Thanks @martst, I merged your PR. However, could you please fix the small layout issue it introduced (details in the PR), so we can publish this version? I'll look at the sample data later as soon as I have a free evening (not so soon! :) )

**Comment by martst** [comment]
I have created a pull request but my inexperience with GIT is showing as I have ended up combining 2 changes in 1 request. I hope that does not cause you a problem.

**Comment by borysiasty** [comment]
Not at all, thanks.

**Comment by borysiasty** [comment]
@martst: the new version 3.6.7 is published, thanks a lot!
