### ISSUE TITLE
Error when saving plot

### ISSUE THREAD

**Issue by jecogeo** [etiennesky/profiletool#16]
Hello dears,

I'm receiving an error when trying to save a plot from profile tool. Sorry if this is not the right way to report an error or get help. Please feel free to point out another way to do it.
Anyway, could you give some clue on this?
I'm using QGIS 2.14.3 in Ubuntu 16.04. Follows de error message from log:

Traceback (most recent call last):
  File "/home/jeco/.qgis2/python/plugins/profiletool/profileplugin.py", line 299, in changePlotLibrary
    self.wdg.addPlotWidget(self.plotlibrary)
  File "/home/jeco/.qgis2/python/plugins/profiletool/ui/ptdockwidget.py", line 147, in addPlotWidget
    mpltoolbar = matplotlib.backends.backend_qt4agg.NavigationToolbar2QTAgg(self.plotWdg, self.frame_for_plot)
AttributeError: 'module' object has no attribute 'NavigationToolbar2QTAgg'

**Comment by patricev** [comment]
I think it is now fixed.
Reopen the Issue it he fix doesn't match your needs.
Regards
