### ISSUE TITLE
Vertical exaggeration + AutoCAD.Format

### ISSUE THREAD

**Issue by borysiasty** [etiennesky/profiletool#19]
_Issue moved from hub.qgis.org
Feature request #12997 Added by Holger Eberhardt 2015-06-18_

I use the tool to derive profiles which are then drawn in AutoCAD. We often draw the profiles with a vertical exaggeration factor. It would be very time saving for us, if the data could be copied to the clipboard in a format that is understood by the AutoCAD "Polyline" command and if we could choose a factor for the vertical exaggeration, that is used as a multiplier for the y-values.

Correct formatting for the Polyline command would require:
- Force "point" as decimal separator, even if the locale setting (in my case "german") says "comma"
- Separate x- and y- values by comma
- Write every pair of x- and y-values to a new line

So the data should look like this
0,14.53
1.2,14.78
2.5,14.66

Much thanks for your work

theudebert

**Comment by patricev** [comment]
Now (V4.0.3) profiletool can export a line to an autocad 3d polyline. Then you can do a profile like you want in autocad. Reopen the issue if this feature does not match your issue
Regards,
