### ISSUE TITLE
Remember last used path while saving the plot

### ISSUE THREAD

**Issue by borysiasty** [etiennesky/profiletool#23]
_Issue moved from hub.qgis.org
Feature request #10643 Added by Mikhail Titov 2014-06-19_

Right now, static function QFileDialog.getSaveFileName is used to browse for a file name for each format. Without default directory provided, one has to navigate to one's folder every time. This is somewhat annoying. I think it would be better if last used folder was reused for all formats. Perhaps this could be achieved by using QFileDialog and its open function, and by making decision on format by looking at returned file extension.

**Comment by patricev** [comment]
fixed in 4.0.1
Regards,
