### ISSUE TITLE
[regression] Inability to profile invisible layer in 3.6.4

### ISSUE THREAD

**Issue by borysiasty** [etiennesky/profiletool#25]
_Issue moved from hub.qgis.org
Bug report #10642 Added by Mikhail Titov 2014-06-19_

In 3.6.4, I'm no longer able to draw profiles for invisible layers (unchecked in QGIS Layers pane). It used to be possible in 3.6.3. I rely on OpenLayers plugin & my feature layers to navigate, and I keep DEM hidden not to distract me.

If selected layer was invisible at the moment plugin was launched, its name does appear in Layer list. However upon double clicking and finishing a path, layer's name just disappears from the Layer list in the plugin. It was non-trivial to figure out it was about layer visibility in QGIS.

**Comment by patricev** [comment]
solved in 4.0.3
