### ISSUE TITLE
Mac vs Phyton/Profile tool

### ISSUE THREAD

**Issue by borysiasty** [etiennesky/profiletool#30]
_Issue moved from hub.qgis.org
Bug report #11262 Added by Fernando Nieto Conde 2014-09-24_

hi there

I have got this message when running plugging Profile tool. Perhaps incomnpatible with Mac?

thx in advance for any help

fer

![sin_titulo](https://cloud.githubusercontent.com/assets/1000043/18026523/e44c6044-6c49-11e6-95dc-6fc902bb6cb7.png)

**Comment by etiennesky** [comment]
Hi this problem seems to come from your installation, the error complains about the numpy versions... nothing to do with this plugin sorry.
