### ISSUE TITLE
export to dxf

### ISSUE THREAD

**Issue by max-trolliet** [etiennesky/profiletool#33]
Hi,

I was wondering if it could be possible to export the graphs in dxf format as we often need this for construction planning. As for now we can only export the graph in pdf or image format, or use the tables... 

Anyway, thanks for the tool!

**Comment by patricev** [comment]
Hi, 
It is now possible to export (4.0.1) a 3d polyline to dxf format. So an elevation profile can be made in ACAD.
Tell me if this solve your issue
Regards,
