### ISSUE TITLE
Error on upgrade to 4.0.1

### ISSUE THREAD

**Issue by dershow** [etiennesky/profiletool#37]
I just upgraded profile tool to 4.0.1 and the upgrade caused an error.  If I restart QGIS, i get the same error.  I'm running on a Mac running OS 10.12.3, with the newest available version of QGIS, 2.18.2.

Here's the error:

Couldn't load plugin profiletool due to an error when calling its classFactory() method 
ImportError: No module named Qt

Traceback (most recent call last):
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 333, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/Users/name/.qgis2/python/plugins/profiletool/__init__.py", line 27, in classFactory
    from .profileplugin import ProfilePlugin
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/name/.qgis2/python/plugins/profiletool/profileplugin.py", line 42, in 
    from .tools.profiletool_core import ProfileToolCore
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/name/.qgis2/python/plugins/profiletool/tools/profiletool_core.py", line 29, in 
    from qgis.PyQt.Qt import *
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ImportError: No module named Qt

Python version: 2.7.10 (default, Jul 30 2016, 19:40:32) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)] 
QGIS version: 2.18.2 Las Palmas, exported 
Python Path:

/Users/name/.qgis2/python/plugins/processing
/Applications/QGIS.app/Contents/MacOS/../Resources/python
/Users/name/.qgis2/python
/Users/name/.qgis2/python/plugins
/Applications/QGIS.app/Contents/MacOS/../Resources/python/plugins
/Library/Frameworks/SQLite3.framework/Versions/C/Python/2.7
/Library/Frameworks/GEOS.framework/Versions/3/Python/2.7/site-packages
/Library/Python/2.7/site-packages/numpy-override
/Library/Python/2.7/site-packages/matplotlib-override
/Library/Frameworks/GDAL.framework/Versions/2.1/Python/2.7/site-packages
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python27.zip
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-old
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload
/Users/name/Library/Python/2.7/lib/python/site-packages
/Library/Python/2.7/site-packages
/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python
/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/PyObjC
/Users/name/.qgis2//python
/Users/name/.qgis2/python/plugins/NNJoin

Thanks,

--Adam

**Comment by adzane** [comment]
same issue on QGIS 2.14, Windows 7: No module named Qt

**Comment by patricev** [comment]
Hi
I fixed the issue in the latest commit. Could you download the code and tell me if it's ok ?
Regards,

**Comment by dershow** [comment]
I just tried to download it and I see the same issue.  But, I was using "manage and install plugins" in QGIS and then did "Reinstall plugin"  Should that get the new version?  Or do I need to do something else to test this?

**Comment by patricev** [comment]
if you're ok do the following : 
First download the code from [https://github.com/etiennesky/profiletool](https://github.com/etiennesky/profiletool) and click on download to get the plugin .zip
Then unzip  in c:\users\\'yourname'\\.qgis2\python\plugins and restart qgis
The plugin must work....
Thank you for doing the beta tester...
Regards,

**Comment by dershow** [comment]
First I uninstalled profile tool, then I quite QGIS, and unzipped, as instructed.  If I then run QGIS, I don't see any error.  But, I don't see the profile tool anyway.  If I then select plugins->manage and control plugins, it now shows as Installed, but shows up in red.  If I click, I see, "This plugin is broken. No module named Qt"  at the top of the page.  It also shows up in the list of Invalid plugins.

**Comment by patricev** [comment]
Arg .... does it display an error message if you start again qgis with the plugin activated ?

**Comment by dershow** [comment]
No.  Although, I'm not sure what "activated" means is this context.  If I unzip it to the correct location then start qgis, I don't get an error or anything.  So, it seems that it doesn't activate.

**Comment by patricev** [comment]
I made a commit . Could you try again to dowload the zip and tell me what's  happening ?

**Comment by dershow** [comment]
Now it does seem to load correctly.  Although, I'm not sure how to get it to actually work.  If I click on the icon, I do get a window.  I can then click back in my terrain window to define a temporary polyline, but I don't see anything like an "Apply" button that should make it calculate and show the profile.  So, when the window first comes up, it has a plot, with no data.  And, that doesn't seem to change as I click lines in my terrain window.

**Comment by adzane** [comment]
It works in Windows now, no more error messages.

**Comment by msweier** [comment]
I was having the same issue on macOS 12.12.3 and QGIS 2.14.10.  Downloading the master worked.  I like the improvements too!  Thanks!
