### ISSUE TITLE
Unusable in QGIS 2.18

### ISSUE THREAD

**Issue by saberraz** [etiennesky/profiletool#40]
The current state of the plugin in QGIS 2.18 is completely broken. 
It keeps coming up with various python error and the only way to get rid of the errors is to kill QGIS.

I suggest to restore to a functional one from the previous releases and pull out the latest version.

**Comment by etiennesky** [comment]
I don't think it would not help in using a previous version, the errors are probably due to changes in QGIS. If you have some changes which fix the problems, please fork the repos and do a pull request. Thanks
