### ISSUE TITLE
Flat terrain curve

### ISSUE THREAD

**Issue by rolfmork** [etiennesky/profiletool#44]
I use Profile tool v4.0.2 (latest) with QGIS 2.18.14 (latest).

Whenever I select a temporary polyline Profile Tool always presents a flat terrain curve (y values 0.0 for all x values) - see attached screen dump.

This happens despite the fact that there are y values (not equal to zero) in the tables tab - however I note that there is a row no. 2 which has zero-values. My guess is Profile Tool presents the zeros in row no.1 instead of the values in row no. 1.

Can anyone fix this (or teach me settings to fix it)?

Thanks a lot!
![image](https://user-images.githubusercontent.com/33415720/32433386-0d18c1f0-c2db-11e7-9351-8c5f5c60f8d6.png)
![image](https://user-images.githubusercontent.com/33415720/32433406-1712fbbc-c2db-11e7-8b2e-8ecd3b38cd33.png)

**Comment by etiennesky** [comment]
Have you tried changing the Selction in the options box? You have Temporary polyline, but you should select one of the 2 bands in your dem file (the first one).

**Comment by rolfmork** [comment]
Thanks a lot for your reply, Etienne.

Not sure what you mean by "dem file" though. I selected Temporary polyline, since I want a custom cut throught the terrain. Btw, as an extra info - when in the table tab I click the button "Copy to clipboard", it only copies zeros (no matter if I select the first or second row in the table first). See attached.

To me it seems like the application is only capturing zeros...
![image](https://user-images.githubusercontent.com/33415720/32436075-2c3fd5c0-c2e3-11e7-8a8b-ce62aeca568f.png)

**Comment by borysiasty** [comment]
Your input raster doesn't contains elevation data in the proper format, it's just contour lines (please google what a DEM raster is). The numbers you see in the table are metres along the profile, and the raster value in all those points is 0, what is apparently true.
