### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by sgalazgarcia** [etiennesky/profiletool#53]
I can't install the plugin -QGIS tells me it is missing a module

<img width="522" alt="screen shot 2018-01-10 at 10 06 47 pm" src="https://user-images.githubusercontent.com/17068439/34806706-a4874160-f652-11e7-8461-ff3fc4896a22.png">

**Comment by borysiasty** [comment]
sgalazgarciaWhat is your QGIS version?

**Comment by borysiasty** [comment]
@sgalazgarcia, what is your QGIS version?
