### ISSUE TITLE
error rubberband QGIS3

### ISSUE THREAD

**Issue by GabrielaOsaciCostache** [etiennesky/profiletool#55]
Hi!
I'm using QGIS 3 (32bit) under Windows 10 (64 bit). Profile Tool 4.0.2 does not work (the line cannot be drawn) and gives the following error:

2018-03-14T20:35:28 WARNING Traceback (most recent call last): 
File "C:/Users/Catalina/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\profiletool\tools\ptmaptool.py", line 78, in moved
self.profiletool.rubberband.addPoint(QgsPoint(self.pointstoDraw[i][0],self.pointstoDraw[i][1]))
TypeError: QgsRubberBand.addPoint(): argument 1 has unexpected type 'QgsPoint'

The plugin works with QGIS 2.18.16 and 2.18.17.

Thanks!

**Comment by pigreco** [comment]
I confirm the error - QGIS 3.0.1 WIN 10 OSGEO4W64

![image](https://user-images.githubusercontent.com/7631137/38464584-5bf680ca-3b10-11e8-901b-ac6dbf87e8c4.png)

**Comment by kylesomerville** [comment]
Also confirmed here - QGIS 3.0.0 WIN10 64.  Plugin is working fine with QGIS 2.18.

**Comment by JaviBecerra** [comment]
Hi,

We solved some issues regarding QGis3 in our repo, you can check it out 
at 
https://github.com/PANOimagen/profiletool/tree/feature/only_profile_at_samples

Regards,

Javier

**Comment by pigreco** [comment]
@JaviBecerra wow, I downloaded the zip and installed in QGIS 3, it works !!!
![image](https://user-images.githubusercontent.com/7631137/38675022-c47ae534-3e56-11e8-8d8e-201e2781cd5c.png)

**Comment by GabrielaOsaciCostache** [comment]
Ciao, Totò...e grazie!
Perdonami l'ignoranza, ma da dove si scarica il file .zip?
Come hai visto sono riuscita a scrivere due parole in inglese (evviva Google Translate!) perché ho bisogno di questo plugin... 
Grazie,Gabriela

      Da: Salvatore Fiandaca <notifications@github.com>
 A: etiennesky/profiletool <profiletool@noreply.github.com> 
Cc: GabrielaOsaciCostache <gabrielacatalinaosaci@yahoo.it>; Author <author@noreply.github.com>
 Inviato: Giovedì 12 Aprile 2018 14:38
 Oggetto: Re: [etiennesky/profiletool] error rubberband QGIS3 (#55)
   
@JaviBecerra wow, I downloaded the zip and installed in QGIS 3, it works !!!

**Comment by pigreco** [comment]
@GabrielaOsaciCostache ciao,
il link è quello di sopra [clicca qui](https://github.com/PANOimagen/profiletool/tree/feature/only_profile_at_samples) e poi guarda questo screen:
![image](https://user-images.githubusercontent.com/7631137/38680303-468e7108-3e66-11e8-8921-3487dd74ff68.png)

**Comment by GabrielaOsaciCostache** [comment]
Thank you! 

      Da: kylesomerville <notifications@github.com>
 A: etiennesky/profiletool <profiletool@noreply.github.com> 
Cc: GabrielaOsaciCostache <gabrielacatalinaosaci@yahoo.it>; Author <author@noreply.github.com>
 Inviato: Giovedì 12 Aprile 2018 12:52
 Oggetto: Re: [etiennesky/profiletool] error rubberband QGIS3 (#55)
   
Also confirmed here - QGIS 3.0.0 WIN10 64. Plugin is working fine with QGIS 2.18.—

**Comment by GabrielaOsaciCostache** [comment]
Thank you! :-))

      Da: Javier Becerra Elcinto <notifications@github.com>
 A: etiennesky/profiletool <profiletool@noreply.github.com> 
Cc: GabrielaOsaciCostache <gabrielacatalinaosaci@yahoo.it>; Author <author@noreply.github.com>
 Inviato: Giovedì 12 Aprile 2018 13:18
 Oggetto: Re: [etiennesky/profiletool] error rubberband QGIS3 (#55)
   
Hi,

We solved some issues regarding QGis3 in our repo, you can check it out 
at 
https://github.com/PANOimagen/profiletool/tree/feature/only_profile_at_samples

Regards,

Javier

**Comment by borysiasty** [comment]
The current maintainers of the plugin are clearly no longer active. I tried to contact them but they don't respond. And I am not involved in its development for years. @JaviBecerra I'd be happy to transfer the plugin ownership in the repository to you, so you can release new versions and switch the metadata.txt to your fork. Would you be interested in this additional burden? :)

**Comment by borysiasty** [comment]
Ok, I've fixed the metadata. In fact the plugin was never compatible with QGIS 3, so starting from version 4.0.3 it's only available for installation in QGIS 2.x. For the 3.x version please install manually the version from @JaviBecerra.

**Comment by GabrielaOsaciCostache** [comment]
Thank You!

      Da: Borys Jurgiel <notifications@github.com>
 A: etiennesky/profiletool <profiletool@noreply.github.com> 
Cc: GabrielaOsaciCostache <gabrielacatalinaosaci@yahoo.it>; Mention <mention@noreply.github.com>
 Inviato: Lunedì 23 Aprile 2018 12:50
 Oggetto: Re: [etiennesky/profiletool] error rubberband QGIS3 (#55)
   
Ok, I've fixed the metadata. In fact the plugin was never compatible with QGIS 3, so starting from version 4.0.3 it's only available for installation in QGIS 2.x. For the 3.x version please install manually the version from @JaviBecerra.—

**Comment by JaviBecerra** [comment]
Hi Borys:

I think that my previous message somehow got lost, I copy-paste it below:

I am not really sure of how much effort we will have to put into this, 
but we are willing to give it a try and become maintainers of the 
plugin. I hope that with a little help from colleagues here at 
PANOimagen we will be able to, at a minimum, keep the code working with 
new QGis versions and, hopefully, add some improvements over time.

As for the process of changing ownership, right now our master branch is 
tracking etiennesky's master. We have some pull requests from other 
branches in our repo pending, should we apply them to our master before 
you change the metadata or wait until you change it and then merge and 
bump the version number?

**Comment by borysiasty** [comment]
Hi @JaviBecerra, thanks a lot! I believe it doesn't really matter which repo is original and which is a fork, so I'd just stick to your repo from now - merging the PRs to your master, and close the pending PRs to the Etienne's one. Then besides bumping the version, you'll need to update the author, email, homepage, tracker and repository tags. I'm just changing the maintainer. Does it sounds good to you?

Do you have an account on plugins.qgis.org (it's basically an OSGeo ID), or should I make user
robertopanoi the maintainer?

The biggest problem is the 18 bug reports and feature requests waiting here. We shouldn't lost track on them, but probably it doesn't make much sense to copy them to your repo (a few of them I already copied from the previous tracker). Of course if you're interested in fixing some of them, let's move those and close them here.

**Comment by JaviBecerra** [comment]
Hi @borysiasty,
My OSGeo ID is javibecerra. I am making the changes you suggested to our repo, i.e.:
-Merging our feature branches to master
-Bumping the version number to 4.1.0
-Updating metadata.txt with our repo url.
Regarding the bug reports/feature requests, we have already made some refactoring that I am certain removed certain crashes. Will check the full list of issues and see if some of them can still be reproduced and move them to our repo. Idem per enhancements.
I see some bugs related to QGis 2.2/2.5 compatibility. Do you know if there is any available test environment to check regressions this far off? We currently check against the latest LTR and current dev versions.
Best regards,
Javier

**Comment by JaviBecerra** [comment]
Hi @borysiasty, we have made the changes to our repo, please check that everything is ok and you can make the change whenever you want.

**Comment by borysiasty** [comment]
Hi @JaviBecerra,
Thanks a lot for saving the world (or at least the plugin users population)!

I've switched the plugin owner to your account, hopefully you can upload a new version now.

I don't know any test environment for ancient QGIS releases (except installing them from http://download.osgeo.org/qgis or https://qgis.org/downloads), but I wouldn't care about versions older than 2.18. So as long as it's not reproducable in 2.18.19, I'd say it's not reproducable ;)

**Comment by GabrielaOsaciCostache** [comment]
Thank you! :)

      Da: Borys Jurgiel <notifications@github.com>
 A: etiennesky/profiletool <profiletool@noreply.github.com> 
Cc: GabrielaOsaciCostache <gabrielacatalinaosaci@yahoo.it>; Mention <mention@noreply.github.com>
 Inviato: Venerdì 4 Maggio 2018 15:31
 Oggetto: Re: [etiennesky/profiletool] error rubberband QGIS3 (#55)
   
Hi @JaviBecerra,
Thanks a lot for saving the world (or at least the plugin users population)!I've switched the plugin owner to your account, hopefully you can upload a new version now.I don't know any test environment for ancient QGIS releases (except installing them from http://download.osgeo.org/qgis or https://qgis.org/downloads), but I wouldn't care about versions older than 2.18. So as long as it's not reproducable in 2.18.19, I'd say it's not reproducable ;)—

**Comment by borysiasty** [comment]
@JaviBecerra,
Could you please upload the new version to https://plugins.qgis.org/plugins/profiletool so we can close this issue?

**Comment by JaviBecerra** [comment]
Hi @borysiasti,

Profile Tool version 4.1.0 with support for QGis 3.0 is out ;)
