### ISSUE TITLE
Qgis 3.10 issue

### ISSUE THREAD

**Issue by Bankifan** [etiennesky/profiletool#63]
Hello, 
First thanks for this perfect tool! 

there is compatibility issues with Qgis 3 : drawing from temporary polyline steal working but from vector --> Qgis don't answer...
I juste an user of Qgis and i'm realy newbie in coding... do you think there is an easy solution to solve the probleme? or all the tools muste be rebuilt?

**Comment by JaviBecerra** [comment]
This issue was reported on https://github.com/PANOimagen/profiletool/issues/35, it has been solved on version 4.1.8.

**Comment by Bankifan** [comment]
Ho yeah i didn't see thanks !
